---
title: "exploracion"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(kableExtra)
library(dplyr)
library(tidyr)
base <- read_excel(
  "../resultados/Desigualdades y acceso a derechos (Respuestas).xlsx")

u<-names(base)
write.csv(u, "nombres_variables.csv")
# a las preguntas de respuesta múltiple gforms les pone coma cuando se eligen varias  

# separo salud
base<-separate(
  base,
  23,
  c("cobertura_salud_1","cobertura_salud_2","cobertura_salud_3","cobertura_salud_4","cobertura_salud_5","cobertura_salud_6","cobertura_salud_7"),
  sep = ",",
  remove = FALSE,
  convert = FALSE,
  extra = "warn",
  fill = "warn")

# separo fuente de ingreso
base<-separate(
  base,
  "6.2 En el último año, los ingresos de las personas provinieron de...?",
  c("fuente_ingreso_1","fuente_ingreso_2","fuente_ingreso_3","fuente_ingreso_4","fuente_ingreso_5","fuente_ingreso_6"),
  sep = ",",
  remove = FALSE,
  convert = FALSE,
  extra = "warn",
  fill = "warn")
# eliminar (en xls) el paréntesis con IFE, progresar, PPP que trae comas que hacen separar coolumnas


```
# Pruebas  

```{r}
class(base$`Nivel Socio Económico`)
table(base$`Nivel Socio Económico`)

base$nse<-as.factor(base$`Nivel Socio Económico`)

base$nse<-factor(base$nse, levels=c("01. Alto", "02. Medio alto", "03.Medio",
                                    "0.4 Medio Bajo", "0.5  Bajo"))
levels(base$nse)<-c("Alto", "Medio alto", "Medio",
                                    "Medio Bajo", "Bajo")

```



```{r}
table(base$`3.1.1 Cantidad de integrantes del hogar`)
# cantidad integrantes está en col 109
table(base$`2.2 ¿Con qué calefaccionan mayormente su casa?` ,
      base$`La vivienda de su casa cuenta con [Gas Natural]`)
kable(table(base[41]))
kable(table(base[42]))


base$ing_hogar<-
  base$`6.1 Me puede decir en promedio, ¿Cuáles son los ingresos totales por mes en el hogar?`

base$ing_hogar<-factor(base$ing_hogar, levels = c("Menos de $25.000",
                                            "Entre $25000 y 55.000",
                                            "Entre $55.000 y $99.000",
                                            "Entre $100.000 y $200.000",
                                            "Más de $200.000"))

kable(table(base$ing_hogar), col.names = c("rango ingresos", "casos"))
table(base$ing_hogar, base$`6.3 En general, sus ingresos mensuales son`)


kable(table(base[52]), col.names = c("origen ingresos", "casos"))

kable(table(base[54]), col.names = c("trabajo en pandemia", "casos"))

kable(table(base$`7.5 Durante el aislamiento social por la pandemia, ¿qué paso mayormente con el trabajo de los miembros de su hogar?`, base$ing_hogar))

kable(table(base[55]), col.names = c("ingresos antes pandemia", "casos"))
kable(table(base[56]), col.names = c("ingresos durante pandemia", "casos"))

addmargins(table(base$`8.1 Antes de la pandemia, ¿los ingresos del hogar eran?`,
      base$`8.2 Y durante la pandemia, ¿los ingresos del hogar son?`))

```



```{r}
kable(table(base$`10.2 Nos podría indicar a qué distancia aproximada de su casa (en cuadras) se ubica el centro de salud que utiliza?`),
      col.names = c("distancia al centro de salud", "casos"))

kable(table(base[69]))
kable(100*round(addmargins(prop.table(table(base$`10.2 Nos podría indicar a qué distancia aproximada de su casa (en cuadras) se ubica el centro de salud que utiliza?`,
            base$nse),2),1),3))
```


```{r}
kable(table(base[66]))

kable(table(base[109]))
table(base[109])

```

```{r}
kable(table(base$fuente_ingreso_1))
kable(table(base$fuente_ingreso_2))
kable(table(base$fuente_ingreso_3))
kable(table(base$fuente_ingreso_4))
kable(table(base$fuente_ingreso_5))
kable(table(base$fuente_ingreso_6))
```

```{r}
kable(table(base$cobertura_salud_1))
kable(table(base$cobertura_salud_2))
kable(table(base$cobertura_salud_3))
kable(table(base$cobertura_salud_4))
kable(table(base$cobertura_salud_5))
kable(table(base$cobertura_salud_6))
kable(table(base$cobertura_salud_7))
```

