---
title: "prueba_cobertura_salud"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reshape2)
library(kableExtra)
library(tidyverse)
library(tidyselect)
library(tidyr)
library(dplyr)
library(ggplot2)
```

```{r}
load("G:/Mi unidad/proyecto_FCS_diciembre_2020/resultados/datos.Rda")
datos$nse<-as.factor(datos$`Nivel Socio Económico`)

datos$nse<-factor(datos$nse, levels=c("01. Alto", "02. Medio alto", "03.Medio",
                                      "0.4 Medio Bajo", "0.5  Bajo"))
levels(datos$nse)<-c("Alto", "Medio alto", "Medio",
                     "Medio Bajo", "Bajo")

table(datos$`3.2 Alguno de los integrantes del hogar tiene... (marcar todas las que señalen)`)


datos<-separate(datos, `3.2 Alguno de los integrantes del hogar tiene... (marcar todas las que señalen)`,
                into=c("cs1", "cs2", "cs3", "cs4"), sep = ",")

datos$cs1<- trimws(datos$cs1, which = "l")
datos$cs2<- trimws(datos$cs2, which = "l")
datos$cs3<- trimws(datos$cs3, which = "l")
datos$cs4<- trimws(datos$cs4, which = "l")


o1<-addmargins(table(datos$cs1, datos$nse),1)
o2<-addmargins(table(datos$cs2, datos$nse),1)
o3<-addmargins(table(datos$cs3, datos$nse),1)
o4<-addmargins(table(datos$cs4, datos$nse),1)

o1_sin_cobertura<-o1[1,]
o1_nsc<-o1[2,]
o1_obra_social<-o1[3,]
o1_otra<-o1[4,]
o1_pami<-o1[5,]
o1_prepaga_os<-o1[6,]
o1_prepaga_pago_voluntario<-o1[7,]
o1_PROFE<-o1[8,]
o1_total<-o1[9,]

o2_sin_cobertura<-o2[1,]
o2_obra_social<-o2[2,]
o2_otra<-o2[3,]
o2_prepaga_os<-o2[4,]
o2_prepaga_pago_voluntario<-o2[5,]
o2_PROFE<-o2[6,]
o2_total<-o2[7,]

o3
o3_sin_cobertura<-o3[1,]
o3_prepaga_os<-o3[2,]
o3_prepaga_pago_voluntario<-o3[3,]
o3_PROFE<-o3[4,]
o3_total<-o3[5,]

o4
o4_sin_cobertura<-o4[1,]
o4_total<-o4[2,]


sin_cobertura<-o1_sin_cobertura+o2_sin_cobertura+o3_sin_cobertura+
  o4_sin_cobertura
ns_nc<-o1_nsc
obra_social<-o1_obra_social+o2_obra_social
otra<-o1_otra+o2_otra
pami<-o1_pami
prepaga_os<-o1_prepaga_os+o2_prepaga_os+o3_prepaga_os
prepaga_voluntario<-o1_prepaga_pago_voluntario+o2_prepaga_pago_voluntario+
  o3_prepaga_pago_voluntario
profe<-o1_PROFE+o2_PROFE+o3_PROFE
total<-o1_total+o2_total+o3_total+o4_total

cobertura_salud<-rbind(obra_social, pami, prepaga_os, prepaga_voluntario, profe, otra, ns_nc,
      sin_cobertura, total)
class(cobertura_salud)
cobertura_salud<-as.data.frame(cobertura_salud)
library(kableExtra)

kable(cobertura_salud)


```

