---
title: "Encuesta a Hogares en torno al acceso a la Salud, la Educacion y el Trabajo"
subtitle: "Análisis descriptivo de las variables seleccionadas"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE, message = FALSE)

```

```{r, include=F, echo=F}
rm(list=ls())
library(reshape2)
library(kableExtra)
library(tidyverse)
library(tidyselect)
datos = read.table("datos_tablas.txt", header = T, sep = "\t")
datos$X = NULL
```

```{r}
x <- list()
i = 10
for(i in 2:ncol(datos)){
datos_ = datos[,c(1,i)]
datos_[[2]]= trimws(datos_[[2]], which = "l")
datos_[[2]] = gsub(", ", ",", datos_[[2]])
valores <- na.omit(unique(unlist(strsplit(as.character(datos_[[2]]), ","))))
ver = separate(datos_, vars_pull(names(datos_), 2), into = as.character(c(1:length(valores))), sep =",")
tabla = melt(ver, id.vars = c("nse"), na.rm = TRUE)
tabla = kable_styling(kable(100*round(
  addmargins(
    prop.table(
      addmargins(
        table(tabla$value, tabla$nse),
        2),2),1),3), 
  caption = paste("Variable - ",names(datos_)[[2]],"(porcentajes por NSE)")), 
  latex_options = "hold_position")
assign(paste0("tabla",i), tabla)
x[[paste("Tabla de frecuencias relativas de la variable",names(datos_)[[2]])]] <- get(paste0("tabla",i))
tabla
}
```


<br></br>

# Tablas de frecuencias de las variables seleccionadas.

```{r}
tabla2
tabla3
tabla4
tabla5
tabla6
tabla7
tabla8
tabla9
tabla10
tabla11
tabla12
```


<br></br>

