---
title: "Tablas nuevas"
author: "Juan Pablo Carranza"
date: "12/5/2021"
output: pdf_document
---

---
title: "Resultados descriptivos"
output: html_document

---

```{r setup, include=FALSE,echo = FALSE, warning = FALSE, message = FALSE}
rm(list=ls())
library(kableExtra)
# setwd("C:/Users/juan/Downloads/")
datos_jp = read.table("Desigualdades y acceso a derechos (Respuestas) - Respuestas de formulario 1.tsv",
                   header = T, sep = "\t", fileEncoding = "UTF-8", check.names=F)

aux <- data.frame(lapply(datos_jp, function(x) {
  sub(", ", " / ", x)}))
colnames(datos_jp) = gsub("\t", " ", colnames(datos_jp))
colnames(aux) <- colnames(datos_jp)
names(datos_jp)
datos_jp = aux ; rm(aux)

#### Tabla dificultades en la continuidad educativa por tipo de establecimiento

which( colnames(datos_jp)=="15.1 Ahora le voy a preguntar sobre las dificultades que hubo en su hogar para sostener la continuidad educativa durante la virtualidad. ¿Tuvieron alguna de estas dificultades? [15.1.1 Falta de conectividad / falta de datos para sostener las actividades virtuales – Si - No]" )
datos_jp$falta_conectividad = datos_jp[,140]
which( colnames(datos_jp)=="15.1 Ahora le voy a preguntar sobre las dificultades que hubo en su hogar para sostener la continuidad educativa durante la virtualidad. ¿Tuvieron alguna de estas dificultades? [15.1.2 No tener dispositivos digitales para sostener las actividades – Si - No]")
datos_jp$falta_dispositivos = datos_jp[,141]
which( colnames(datos_jp)=="15.1 Ahora le voy a preguntar sobre las dificultades que hubo en su hogar para sostener la continuidad educativa durante la virtualidad. ¿Tuvieron alguna de estas dificultades? [15.1.3 Dispositivos digitales insuficientes para sostener las actividades de los distintos miembros del hogar – Si - No]" )
datos_jp$dispositivos_insuficientes = datos_jp[,142]
datos_jp$falta_espacios = datos_jp[,143]
datos_jp$conocimiento_dispositivos_acompanantes = datos_jp[,144]
datos_jp$dificultades_economicas = datos_jp[,145]
datos_jp$dificultades_tiempo = datos_jp[,146]
datos_jp$otras_dificultades = datos_jp[,140]


which( colnames(datos_jp)=="14.2 A qué tipo de establecimiento, público o privado, asisten? [Preescolar]")
datos_jp$preescolar = datos_jp[,79]
which( colnames(datos_jp)=="14.2 A qué tipo de establecimiento, público o privado, asisten? [Primario]")
datos_jp$primario = datos_jp[,80]
datos_jp$secundario = datos_jp[,81]
datos_jp$universitario = datos_jp[,82]

aux = datos_jp[,c("falta_conectividad","falta_dispositivos","dispositivos_insuficientes",
                 "falta_espacios","conocimiento_dispositivos_acompanantes",
                 "dificultades_economicas","dificultades_tiempo","otras_dificultades",
                 "preescolar","primario","secundario","universitario")]
aux$id_hogar = 1:nrow(aux)
library(reshape2)
aux = melt(aux, id.vars = c("id_hogar","preescolar","primario","secundario","universitario"))
aux = dplyr::rename(aux, dificultad = variable, valor = value)
aux = subset(aux, valor=="Sí")
aux = melt(aux, id.vars = c("id_hogar","dificultad","valor"))
aux = subset(aux, value=="Público" | value=="Privado")
names(aux)
aux = dplyr::rename(aux, nivel = variable, condicion = value)
aux = aux[,c("id_hogar","dificultad","nivel","condicion")]




#### Tabla género del principal aportante
which( colnames(datos_jp)=="Quién aporta el principal ingreso?")
which( colnames(datos_jp)=="1.2 Género")


datos_jp$sexo_aportante = ifelse(datos_jp[,110]=="Padre de famiilia" |
                                (datos_jp[,110]=="Uno mismo" &
                                   datos_jp[,5]=="Varón"), "Varón",
                                 ifelse(datos_jp[,110]=="Madre de familia" |
                                          (datos_jp[,110]=="Uno mismo" &
                                             datos_jp[,5]=="Mujer"), "Mujer","No especificado"))

### 


datos_jp$nse<-as.factor(datos_jp$"Nivel Socio Económico")

datos_jp$nse<-factor(datos_jp$nse, levels=c("01. Alto", "02. Medio alto", "03.Medio",
                                      "0.4 Medio Bajo", "0.5  Bajo"))
levels(datos_jp$nse)<-c("Alto", "Medio alto", "Medio",
                     "Medio Bajo", "Bajo")


```



```{r message=FALSE, warning=FALSE, echo=F}

kable_styling(kable(100*round(addmargins(prop.table(addmargins(table(aux$dificultad, aux$condicion),2),2),1),3), caption = "Dificultades en la continuidad educativa (porcentajes por tipo de establecimiento)"), latex_options = "HOLD_position")
kable_styling(kable(addmargins(table(aux$dificultad, aux$condicion)), caption = "Dificultades en la continuidad educativa por tipo de establecimiento (absolutos)"), latex_options = "HOLD_position")

###
kable_styling(kable(100*round(addmargins(prop.table(addmargins(table(datos_jp$sexo_aportante, datos_jp$nse),2),2),1),3), caption = "Sexo del principal aportante de ingresos del hogar (porcentajes por NSE)"), latex_options = "HOLD_position")
kable_styling(kable(addmargins(table(datos_jp$sexo_aportante, datos_jp$nse)), caption = "Sexo del principal aportante de ingresos del hogar (absolutos)"), latex_options = "HOLD_position")


```
